
import * as d from './components';

export const DIRECTIVES = [
  d.PdAlert,
  d.PdAnimation,
  d.PdBackdrop,
  d.PdButton,
  d.PdButtonGroup,
  d.PdCheckbox,
  d.PdChip,
  d.PdCombobox,
  d.PdDatepicker,
  d.PdDropdown,
  d.PdDropdownItem,
  d.PdIcon,
  d.PdInput,
  d.PdLabel,
  d.PdList,
  d.PdListItem,
  d.PdListItemExpandable,
  d.PdMenu,
  d.PdMenuItem,
  d.PdModal,
  d.PdNavbar,
  d.PdNavbarItem,
  d.PdPanel,
  d.PdPanelContent,
  d.PdPanelFooter,
  d.PdPanelHeader,
  d.PdProgressBar,
  d.PdRadio,
  d.PdRadioGroup,
  d.PdSearch,
  d.PdSidebar,
  d.PdSidebarItem,
  d.PdSkeleton,
  d.PdSlider,
  d.PdSort,
  d.PdTable,
  d.PdTableFilter,
  d.PdTabs,
  d.PdTextarea
];
