name: Deployment
on:
    push:
        branches:
            - master
    watch:
        types: [started]
jobs:
    build:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v2
            - name: npm install
              run: npm install
            - name: build stencil
              run: npm run build
            - name: test stencil
              run: npm run test
            - name: build storybook
              run: npm run build-storybook
    deployment:
        runs-on: self-hosted
        needs: build
        steps:
            - name: delete dest
              run: rm -rf /var/www/parlament/*
            - name: copy storybook
              run: cp -r storybook-static/* /var/www/parlament
            - name: mkdir build
              run: mkdir /var/www/parlament/build
            - name: copy stencil
              run: cp -r dist/parlamentsdienstecore/* /var/www/parlament/build
            - name: copy assets
              run: cp -r src/assets /var/www/parlament
            - name: mkdir vue
              run: mkdir /var/www/parlament/vue
            - name: copy vue
              run: cp -r src/vue.html /var/www/parlament/vue/index.html
